POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "description": "test",
    "date": "2025-12-12",
    "specialist": "Dr. Nick",
    "diagnosisCodes": ["Z57.1", "Z74.3"],
    "type": "HealthCheck",
    "healthCheckRating": 15
}

###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667
Content-Type: application/json