POST https://fullstackopen-phonebook-i2xi.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-243563"
}

###
GET https://fullstackopen-phonebook-i2xi.onrender.com/api/persons