GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/683b23fce6b3b10b822693d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4MzM0MWY0ODc1NTIxMDM4MzYwYWZkOSIsImlhdCI6MTc0ODcwNTg0MywiZXhwIjoxNzQ4NzA5NDQzfQ.XLVUKT9UgSMRdVJAdeFDrVqGNfAbtd52HXbCtSjmvMY

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4MzM0MWY0ODc1NTIxMDM4MzYwYWZkOSIsImlhdCI6MTc0ODcwNTg0MywiZXhwIjoxNzQ4NzA5NDQzfQ.XLVUKT9UgSMRdVJAdeFDrVqGNfAbtd52HXbCtSjmvMY

{
    "title": "rest delete",
    "author": "root",
    "url": "https://nowhere.com",
    "likes": 1
}

###
PUT http://localhost:3001/api/blogs/5a422ba71b54a676234d17fb
Content-Type: application/json

{
  "title": "New update",
  "author": "Faith",
  "url": "https://newupdate.com"
}