GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "testing user",
  "name": "test_user",
  "password": "test_password"
}

###
POST http://localhost:3001/api/testing/reset